language: python
python:
  - "2.7"
sudo: false
install:
  - git clone --depth=1 --branch=master https://github.com/tabatkins/bikeshed.git ./bikeshed
  - pip install pygments
  - pip install --editable ./bikeshed
  - bikeshed update
script:
  bikeshed spec ./index.bs
